# Generated by Django 4.2.7 on 2026-08-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phone'),
        ('account', '0005_pendingregistration_phone'),
    ]

    operations = [
    ]
