# Generated by Django 4.2.7 on 2026-04-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lecture_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
