# Generated by Django 4.2.7 on 2026-08-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_course_id_alter_quiz_lecture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
