# Generated by Django 4.2.7 on 2025-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_lecture_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
