# Generated by Django 4.2.7 on 2025-12-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_lecture_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='summary_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
